name: Playwright Tests with Allure on EC2

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Playwright with Allure on EC2
    runs-on: self-hosted

    container:
      image: mcr.microsoft.com/playwright:v1.44.0-jammy
      options: --entrypoint ""  # Optional: override default entrypoint to use bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  
          java-version: '17'       

      - name: Verify Java installation
        run: |
          java -version
          javac -version

      - name: Install dependencies and run tests
        run: |
          npm ci
          npm install -D allure-playwright
          npx playwright install --with-deps
          npx playwright test --reporter=line,allure-playwright
          npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
